
SECRET_KEY = ";sp1N8UP@TDA$&X]Hit^rx[2"

MONGODB_DB = 'kun'
MONGODB_HOST = '127.0.0.1'
MONGODB_PORT = 27017

CELERY_BROKER_URL='redis://localhost:6379/0'
CELERY_RESULT_BACKEND='redis://localhost:6379/0'
CELERY_TRACK_STARTED=True
CELERY_IGNORE_RESULT=False